//
const PATH = 'src/assets/images/';

export default {
  TWITTER_LOGO: require(`${PATH}twitter-logo.png`),
  ICON_STARS: require(`${PATH}icon-stars.png`),
  ICON_SETTINGS: require(`${PATH}icon-setting.png`),
  AVATAR: require(`${PATH}avatar.png`),
  ERIN: require(`${PATH}erin.png`),
  ICON_PROFILE: require(`${PATH}icon-profile.png`),
  ICON_LISTS: require(`${PATH}icon-lists.png`),
  ICON_TOPICS: require(`${PATH}icon-topics.png`),
  ICON_BOOKMARKS: require(`${PATH}icon-bookmarks.png`),
  ICON_MOMENTS: require(`${PATH}icon-moments.png`),
  ICON_LAMP: require(`${PATH}icon-lamp.png`),
  ICON_CODE: require(`${PATH}icon-code.png`),
  ICON_ACCOUNT: require(`${PATH}icon-account.png`),
  ICON_REPLY: require(`${PATH}icon-reply.png`),
  ICON_RETWEET: require(`${PATH}icon-retweet.png`),
  ICON_HEART: require(`${PATH}icon-heart.png`),
  ICON_SHARE: require(`${PATH}icon-share.png`),
  ICON_VERIFY: require(`${PATH}icon-verify.png`),
  ICON_SPHERE: require(`${PATH}icon-sphere.png`),
  ARROW: require(`${PATH}arrow.png`),
  ARROW_RIGHT: require(`${PATH}arrow-right.png`),
  ICON_ALERT: require(`${PATH}icon-alert.png`),
  ICON_HAPPENING: require(`${PATH}icon-happening.png`),
  ICON_NEW_MESSAGE: require(`${PATH}icon-new-message.png`),
  ICON_STAR: require(`${PATH}icon-star.png`),

  AVATAR1: require(`${PATH}contents/avatar1.png`),
  AVATAR2: require(`${PATH}contents/avatar2.png`),
  AVATAR3: require(`${PATH}contents/avatar3.png`),
  IMAGE1: require(`${PATH}contents/image1.jpg`),
  IMAGE2: require(`${PATH}contents/image2.jpeg`),
  IMAGE3: require(`${PATH}contents/image3.jpeg`),
};
