// TAB
export const HOME_SCREEN = 'TAB_HOME_SCREEN';
export const SEARCH_SCREEN = 'TAB_SEARCH_SCREEN';
export const NOTIFICATIONS_SCREEN = 'TAB_NOTIFICATIONS_SCREEN';
export const MESSAGES_SCREEN = 'MESSAGES_SCREEN';

// DRAWER
export const DRAWER_SCREEN = 'DRAWER_SCREEN';
